### PR TITLE
fix-issue: add seo wrapper to each page / remove prev and next button in mobile view

### PR DESCRIPTION
**Pull request by raymondtju**
Closes 
https://github.com/zakiego/desa-bambangin-2023/issues/3
https://github.com/zakiego/desa-bambangin-2023/issues/2

Task: 
- add seo wrapper to each page
- hide the Previous button on the first page and the Next button on the last page

### CODE REVIEW

**Comment by zakiego** [comment]
Thank you @raymondtju. I will check it soon. For now, the error is occurring because the pnpm-lock is not updated, either because pnpm-install has not been executed or the latest pnpm-lock has not been pushed

image

**Comment by raymondtju** [comment]
> 

When I am running the `pnpm i` command, seems that I stuck on this
`WARN  Moving @heroicons/react that was installed by a different package manager to "node_modules/.ignored"`

Is there any solution through this? Thanks

Edit:
Seems that the error successfully fix by reinstall using `pnpm` instead of `npm`😉

**Comment by zakiego** [comment]
LGTM 🚀

This is beyond expectations, really great. I apologize if my code is messy as this project was done in a hurry 😅

Thank you, @raymondtju!

**Comment by raymondtju** [comment]
Thank you too @zakiego for the issue !

Your code is not as messy as you expected, it's all good, got a few knowledge. 
Anyway I also just know that we can make static content using keystatic too!

**Pull request merged**
